all: analogAveraging analogRead analogWrite digitalRead digitalWrite FindDevices freqPWM getVersion levelRead NewAddress pinMode pinOutScheme pinPull reset servoAttach servoWrite servoWriteMicroseconds
analogAveraging         :analogAveraging.cpp ../iarduino_I2C_Expander.cpp
analogRead              :analogRead.cpp ../iarduino_I2C_Expander.cpp
analogWrite             :analogWrite.cpp ../iarduino_I2C_Expander.cpp
digitalRead             :digitalRead.cpp ../iarduino_I2C_Expander.cpp
digitalWrite            :digitalWrite.cpp ../iarduino_I2C_Expander.cpp
FindDevices             :FindDevices.cpp ../iarduino_I2C_Expander.cpp
freqPWM                 :freqPWM.cpp ../iarduino_I2C_Expander.cpp
getVersion              :getVersion.cpp ../iarduino_I2C_Expander.cpp
levelRead               :levelRead.cpp ../iarduino_I2C_Expander.cpp
NewAddress              :NewAddress.cpp ../iarduino_I2C_Expander.cpp
pinMode                 :pinMode.cpp ../iarduino_I2C_Expander.cpp
pinOutScheme            :pinOutScheme.cpp ../iarduino_I2C_Expander.cpp
pinPull                 :pinPull.cpp ../iarduino_I2C_Expander.cpp
reset                   :reset.cpp ../iarduino_I2C_Expander.cpp
servoAttach             :servoAttach.cpp ../iarduino_I2C_Expander.cpp
servoWrite              :servoWrite.cpp ../iarduino_I2C_Expander.cpp
servoWriteMicroseconds  :servoWriteMicroseconds.cpp ../iarduino_I2C_Expander.cpp

clean:
	rm -f analogAveraging analogRead analogWrite digitalRead digitalWrite FindDevices freqPWM getVersion levelRead NewAddress pinMode pinOutScheme pinPull reset servoAttach servoWrite servoWriteMicroseconds
